### ISSUE TITLE
setOpen(true) doesn't seem to work

### ISSUE THREAD

**Issue by costyn** [helgastogova/react-stateful-bottom-sheet#1]
Hello!
First of all, very nice library, thanks for sharing.

I'm trying to also include a button on the drawer which will open the drawer which will have search filters on it. Doing a setOpen(true) doesn't seem to work, unfortunately (while setOpen(false) does).

```			
<BottomSheet>
  {({ isOpen, setOpen }) => (
	  <div>
		  <FilterTagGroup onChange={onChangeSelect} urlSearchParams={urlSearchParams} />
		  <ButtonSecondary
			  variant={'on-light'}
			  onClick={() => setOpen(!isOpen)}>
			  {isOpen ? 'Close Filters' : 'Open Filters'}
		  </ButtonSecondary>
	  </div>
  )}
</BottomSheet>
```

Am I doing something wrong?

Thanks

**Comment by helgastogova** [comment]
Hi @costyn, thank you for your report. checking...

**Comment by helgastogova** [comment]
checked, 

@costyn thank you again 🙌 , 
[made a fix](https://github.com/helgastogova/react-stateful-bottom-sheet/pull/2) 

please update to 1.1.8 and everything should be fine

checked it [here](https://codesandbox.io/p/sandbox/eager-cannon-rs9jhl?file=%2Fsrc%2FApp.tsx%3A6%2C26) with a new version

**Comment by costyn** [comment]
Hi @helgastogova, that was very, very quick! I had made the same fix to local copy, works fine yes!
