### ISSUE TITLE
Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by costyn** [helgastogova/react-stateful-bottom-sheet#3]
Hello again!

When updating from 1.0.7 to 1.0.8, I now get a "index.js:481 React Router caught the following error during render TypeError: Cannot read properties of null (reading 'useRef')" which is referring to the useRef  in index.tsx line 36. 

Rolling back to 1.0.7 makes this error go away, I've been trying to troubleshoot, but am not experienced enough in React/TypeScript to spot the issue.

Also 'fullHeight' is missing from the useEffect deps on line 43.

Cheers

**Comment by costyn** [comment]
Nevermind, it seems there was an issue with different React versions. I've now updated the packages for react-stateful-bottom-sheet and used npm pack and then added the file to my project. Now it works. 

I'll submit a PR later.

**Comment by helgastogova** [comment]
Hi again!

>Also 'fullHeight' is missing from the useEffect deps on line 43.

yes, thank you, was fixing the prev issue on the run, fixing :) 

What is about React versions, which one do you use?

**Comment by costyn** [comment]
> What is about React versions, which one do you use?

18.2.0, which, as far as i can tell, is what your project also uses. So I'm not quite sure it was a React version conflict. 

Speaking of versions, npm audit reports some issues with your project at the moment ;)

**Comment by helgastogova** [comment]
>Speaking of versions, npm audit reports some issues with your project at the moment ;)

@costyn thank you! fixed

**Comment by helgastogova** [comment]
>Cannot read properties of null (reading 'useRef')" which is referring to the useRef in index.tsx line 36.

Will try to find a reason a little bit later

**Comment by costyn** [comment]
It might just been some weirdness when using npm link in your library and yarn link in my project. I wouldn't commit too much time to it. 

EDIT: Although that doesn't explain why I still got the useRef when using your 1.0.8 version from public npm repo

**Comment by costyn** [comment]
I saw you added new commits and released 1.0.11. Everything seems to work fine now with that version. 💯 🚀

**Comment by helgastogova** [comment]
@costyn amazing! Should we close the issue then or we have something else?

**Comment by costyn** [comment]
Yes, fine as it is now :)
